run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - govet
    - gofmt
    - goimports
    - staticcheck
    - gocyclo
    - goconst
    - gosec
    - errcheck
    - ineffassign
    - gosimple
    - typecheck
    - unused
    - revive
  disable:
    - deadcode

linters-settings:
  gocyclo:
    min-complexity: 18
  revive:
    severity: warning
    rules:
      - name: var-naming
      - name: indent-error-flow
      - name: superfluous-else
  gosec:
    excludes:
      - G304 # false positives: path comes from controlled sources
      - G112 # covered by server timeouts

issues:
  exclude-use-default: false
  exclude:
    - 'should have comment or be unexported'
  max-same-issues: 0
  max-issues-per-linter: 0

