apiVersion: v1
kind: ConfigMap
metadata:
  name: highload-config
  namespace: highload-microservice
data:
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "8080"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "highload_db"
  DB_SSLMODE: "disable"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
  REDIS_DB: "0"
  KAFKA_BROKERS: "kafka-service:9092"
  KAFKA_TOPIC: "user-events"
  KAFKA_GROUP_ID: "highload-service"
  LOG_LEVEL: "info"


