replicaCount: 1

image:
  repository: highload-microservice
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  USE_TLS: "false"
  DDOS_PROTECTION_ENABLED: "false"
  RATE_LIMIT_REQUESTS_PER_MINUTE: "600"
  RATE_LIMIT_BURST_SIZE: "100"
  RATE_LIMIT_AUTH_REQUESTS_PER_MINUTE: "60"
  RATE_LIMIT_AUTH_BURST_SIZE: "20"

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: highload.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

